### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by Anamichel-leon** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Anamichel-leon#1]
[Infografia calidad y diferentes pruebas --Ana Michel Leon Leon.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Anamichel-leon/files/15463754/Infografia.calidad.y.diferentes.pruebas.--Ana.Michel.Leon.Leon.pdf)

**Comment by josealfredo79** [comment]
No se puede visualizar...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
